/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/MeetUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/PreferencesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SwipeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/MeetUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/PreferencesScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/SwipeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/WelcomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/HomeScreen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `/MeetUpScreen${`?${string}` | `#${string}` | ''}` | `/PreferencesScreen${`?${string}` | `#${string}` | ''}` | `/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/SwipeScreen${`?${string}` | `#${string}` | ''}` | `/WelcomeScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/MeetUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/PreferencesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SwipeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
